logging:
  level:
    com.dnas.redbox.migration: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost/test_db
    username: postgres
    password: postgres
  flyway:
    locations: "classpath:db/migration"
    #https://flywaydb.org/documentation/configuration/parameters/baselineOnMigrate
    baselineOnMigrate: true
    skipDefaultResolvers: true